// Mock data for frontend-only development
export const mockProfile = {
  id: "user-123",
  first_name: "John",
  last_name: "Doe",
  email: "john@example.com",
  phone: "+1 (555) 123-4567",
  kyc_status: "verified" as const,
  created_at: "2024-01-15",
  role: "borrower" as const,
}

export const mockLoans = [
  {
    id: "loan-001",
    user_id: "user-123",
    product_id: "prod-001",
    amount: 5000,
    duration_months: 12,
    interest_rate: 8.5,
    status: "active" as const,
    monthly_payment: 438.5,
    created_at: "2024-06-01",
    due_date: "2025-06-01",
    paid_amount: 1315.5,
  },
  {
    id: "loan-002",
    user_id: "user-123",
    product_id: "prod-002",
    amount: 2000,
    duration_months: 6,
    interest_rate: 7.5,
    status: "completed" as const,
    monthly_payment: 340,
    created_at: "2024-01-01",
    due_date: "2024-07-01",
    paid_amount: 2040,
  },
]

export const mockLoanProducts = [
  {
    id: "prod-001",
    name: "Personal Loan",
    description: "Quick personal loans for any purpose",
    min_amount: 1000,
    max_amount: 50000,
    min_duration: 3,
    max_duration: 60,
    interest_rate: 8.5,
    features: ["Fast approval", "Flexible repayment", "No collateral required"],
  },
  {
    id: "prod-002",
    name: "Business Loan",
    description: "Loans for small business expansion",
    min_amount: 5000,
    max_amount: 100000,
    min_duration: 6,
    max_duration: 84,
    interest_rate: 7.5,
    features: ["Business growth", "Competitive rates", "Quick disbursement"],
  },
  {
    id: "prod-003",
    name: "Education Loan",
    description: "Finance your education dreams",
    min_amount: 2000,
    max_amount: 75000,
    min_duration: 12,
    max_duration: 120,
    interest_rate: 6.5,
    features: ["Education focused", "Grace period", "Low interest"],
  },
  {
    id: "prod-004",
    name: "Emergency Loan",
    description: "Quick cash for emergencies",
    min_amount: 500,
    max_amount: 10000,
    min_duration: 1,
    max_duration: 12,
    interest_rate: 12.0,
    features: ["Instant approval", "Same day disbursement", "Minimal documentation"],
  },
  {
    id: "prod-005",
    name: "Home Improvement Loan",
    description: "Upgrade your living space",
    min_amount: 3000,
    max_amount: 75000,
    min_duration: 12,
    max_duration: 60,
    interest_rate: 7.0,
    features: ["Home focused", "Flexible terms", "Competitive rates"],
  },
  {
    id: "prod-006",
    name: "Debt Consolidation",
    description: "Consolidate multiple debts into one",
    min_amount: 5000,
    max_amount: 100000,
    min_duration: 12,
    max_duration: 84,
    interest_rate: 6.8,
    features: ["Simplify payments", "Lower rates", "Improve credit"],
  },
]

export const mockKYCDocuments = [
  {
    id: "doc-001",
    user_id: "user-123",
    document_type: "id",
    status: "approved" as const,
    file_url: "/id-document.png",
    uploaded_at: "2024-01-10",
    verified_at: "2024-01-12",
  },
  {
    id: "doc-002",
    user_id: "user-123",
    document_type: "proof_of_address",
    status: "approved" as const,
    file_url: "/address-proof.jpg",
    uploaded_at: "2024-01-11",
    verified_at: "2024-01-13",
  },
  {
    id: "doc-003",
    user_id: "user-123",
    document_type: "income_proof",
    status: "pending" as const,
    file_url: "/income-proof.jpg",
    uploaded_at: "2024-01-14",
    verified_at: null,
  },
]

export const mockFraudAlerts = [
  {
    id: "fraud-001",
    loan_id: "loan-003",
    user_id: "user-456",
    risk_score: 75,
    flags: ["Multiple recent applications", "High amount for profile"],
    status: "pending" as const,
    created_at: "2024-10-25",
  },
  {
    id: "fraud-002",
    loan_id: "loan-004",
    user_id: "user-789",
    risk_score: 45,
    flags: ["Incomplete KYC"],
    status: "reviewed" as const,
    created_at: "2024-10-24",
  },
]

export const mockPayments = [
  {
    id: "pay-001",
    loan_id: "loan-001",
    amount: 438.5,
    payment_method: "card",
    status: "completed" as const,
    transaction_hash: "0x1234567890abcdef",
    created_at: "2024-10-01",
  },
  {
    id: "pay-002",
    loan_id: "loan-001",
    amount: 438.5,
    payment_method: "bank_transfer",
    status: "completed" as const,
    transaction_hash: "0xabcdef1234567890",
    created_at: "2024-09-01",
  },
  {
    id: "pay-003",
    loan_id: "loan-001",
    amount: 438.5,
    payment_method: "crypto",
    status: "completed" as const,
    transaction_hash: "0x9876543210fedcba",
    created_at: "2024-08-01",
  },
]

export const mockInstitutionProfile = {
  id: "inst-001",
  name: "FinFlow Microfinance",
  email: "admin@finflow.com",
  phone: "+1 (555) 987-6543",
  role: "institution" as const,
  created_at: "2023-01-01",
}

export const mockInstitutionStats = {
  total_loans_issued: 1250,
  total_amount_disbursed: 12500000,
  active_loans: 856,
  approved_loans: 1200,
  pending_applications: 45,
  total_products: 6,
}
